### ISSUE TITLE
Case file differences

### ISSUE THREAD

**Issue by microfortnight** [snsten/Klein#2]
Really like this board with all the best features from Dilemma, KLOR and others.

Can you point out the differences between the case files?

I understand that the [case-KleinCase.stl](https://github.com/snsten/Klein/blob/main/Case/case-KleinCase.stl) file includes cutouts for USB, TRRS, everything what's needed for the wired version.

Regarding the [case-KleinCase-Wireless.stl](https://github.com/snsten/Klein/blob/main/Case/case-KleinCase-Wireless.stl), might be a dumb question, but it does not seem to have the USB-Connector cutout at the back, isn't this a problem when charging the battery?

What about the temp and 4mm pad file? Thanks in advance!

**Comment by snsten** [comment]
Removed extra case files now there's only switchplate, wired and wireless case files.

The usb cutout was removed since if you socket the board like [this](https://www.40percent.club/2018/03/sockets.html) the usb is elevated wrt PCB. 
Added the cutout again so that if someone solders the board directly on PCB then the cutout will be required.

**Comment by microfortnight** [comment]
Thanks for the clarification 👍
