### ISSUE TITLE
OLED i2c pinout mislabeled or misrouted

### ISSUE THREAD

**Issue by idesignstuff** [snsten/Klein#6]
![image](https://user-images.githubusercontent.com/16802585/201153154-467b552f-b7a2-416d-a9d5-180da191a33f.png)
In my (very limited) experience with PCB design, the square pad = GND and the pinout for a OLED on Amazon appears to have the GND pin in the first position. 
![image](https://user-images.githubusercontent.com/16802585/201153737-de936db3-46ff-44e5-ba6c-38220d1b4acf.png)
My hypothesis is that the Silkscreen just needs to match the pinout.

**Comment by snsten** [comment]
Don't follow the silkscreen for the old PCB gerbers, for both L and R the order is SDA SCL VCC GND 
Fixed the silkscreen labels in the latest commit, the routing is fine just have to bridge the appropriate jumpers for L/R sides.

On R side the GND will be the square pad
![R-Side](https://user-images.githubusercontent.com/42868640/201288356-f0e565e4-1587-4212-af2b-74137bebf3fc.png)

On L side SDA will be the square pad due to flipping of PCB.
![L-Side](https://user-images.githubusercontent.com/42868640/201288458-77e42e49-56a8-4fdb-b7a7-920d842463cb.png)

**Comment by idesignstuff** [comment]
Boards were shipped this week, so I'll roll with it.

**Comment by idesignstuff** [comment]
So, I'm hoping to get an OLED on the left (peripheral) side. The first rev PCB's I'm using have no VCC voltage on the left side OLED pins, but it's there on the touchpad pins.
As the OLED mounts upside down, the pins are all wrong according to the silk on the left side.
they would need to be in the same arrangement (SDA,SCL,VCC,GND) on the keys side of the left board, just like they are on the keys side of the righthand board. As you have a set of jumpers for each side, this looks possible, but I haven't learned kicad yet to check... 
As a bit of encouragement, I'm typing this on my Klein build!
